In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [7]:
flat[0:5]#same as flat[0:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
b = flat

In [11]:
array([4, 5, 6, 7])

NameError: name 'array' is not defined

In [12]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6]) 

In [ ]:
arr [[]]