In [6]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [9]:
arr[0][1]


np.int64(2)

In [11]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [12]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [ ]:
arr[0][1]

In [ ]:
arr[0:2, 1:3]

In [13]:
arr3D = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
[[7, 8, 9],
 [10, 11, 12]]

])

In [ ]:
print(arr3D[:, 0, :])

In [14]:
arr3D


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])