In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 #Vectorizatio
print(result) #output

[ 1  4  9 16 25]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 4 #Vectorizatio
print(result) #output

[  1  16  81 256 625]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 4 #Vectorizatio
print(result) #output

[  1  16  81 256 625]


In [6]:
result + 10

array([ 11,  26,  91, 266, 635])

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
print(result) #output

[[2 4 6]
 [5 7 9]]


In [ ]:
data = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])
