In [1]:
import numpy as shreya
arr = shreya.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])


In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3: 6]

array([4, 5, 6])

In [7]:
flat[:5] #same as flat[0:5}

array([1, 2, 3, 4, 5])